name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  kakao_flutter_sdk: ^1.9.7+3
  change_app_package_name: ^1.5.0
  provider: ^6.1.1  # Provider 패키지 추가
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  table_calendar: ^3.1.3  
  intl: ^0.19.0 
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family : Anemone_air
      fonts : 
        - asset : assets/fonts/Anemone_air.ttf
    - family: Anemone
      fonts:
        - asset: assets/fonts/Anemone.ttf